application: peurpleme
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /css
  static_dir: css
  
- url: /_ah/xmpp/message/chat/
  script: xmpp.py

- url: /admin/.*
  script: admin.py
      
- url: .*
  script: main.py

